version: '3'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: wanikani
      POSTGRES_USER: wk_user
      POSTGRES_PASSWORD: wk_pass

  api:
    build: ./
    depends_on:
      - db
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: "postgres://wk_user:wk_pass@db/wanikani?sslmode=disable"
